%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clear all
tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'multivariate_uoc_v1';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('multivariate_uoc_v1.log');
M_.exo_names = 'e_irr1';
M_.exo_names_tex = '\epsilon_{1t}';
M_.exo_names_long = 'e_irr1';
M_.exo_names = char(M_.exo_names, 'e_irr2');
M_.exo_names_tex = char(M_.exo_names_tex, '\epsilon_{2t}');
M_.exo_names_long = char(M_.exo_names_long, 'e_irr2');
M_.exo_names = char(M_.exo_names, 'e_irr3');
M_.exo_names_tex = char(M_.exo_names_tex, '\epsilon_{3t}');
M_.exo_names_long = char(M_.exo_names_long, 'e_irr3');
M_.exo_names = char(M_.exo_names, 'e_lev1');
M_.exo_names_tex = char(M_.exo_names_tex, '\eta_{1t}');
M_.exo_names_long = char(M_.exo_names_long, 'e_lev1');
M_.exo_names = char(M_.exo_names, 'e_lev2');
M_.exo_names_tex = char(M_.exo_names_tex, '\eta_{2t}');
M_.exo_names_long = char(M_.exo_names_long, 'e_lev2');
M_.exo_names = char(M_.exo_names, 'e_lev3');
M_.exo_names_tex = char(M_.exo_names_tex, '\eta_{3t}');
M_.exo_names_long = char(M_.exo_names_long, 'e_lev3');
M_.exo_names = char(M_.exo_names, 'e_slp1');
M_.exo_names_tex = char(M_.exo_names_tex, '\zeta_{1t}');
M_.exo_names_long = char(M_.exo_names_long, 'e_slp1');
M_.exo_names = char(M_.exo_names, 'e_slp2');
M_.exo_names_tex = char(M_.exo_names_tex, '\zeta_{2t}');
M_.exo_names_long = char(M_.exo_names_long, 'e_slp2');
M_.exo_names = char(M_.exo_names, 'e_slp3');
M_.exo_names_tex = char(M_.exo_names_tex, '\zeta_{3t}');
M_.exo_names_long = char(M_.exo_names_long, 'e_slp3');
M_.exo_names = char(M_.exo_names, 'e_cyc1');
M_.exo_names_tex = char(M_.exo_names_tex, '\kappa_{1t}');
M_.exo_names_long = char(M_.exo_names_long, 'e_cyc1');
M_.exo_names = char(M_.exo_names, 'e_cyc2');
M_.exo_names_tex = char(M_.exo_names_tex, '\kappa_{2t}');
M_.exo_names_long = char(M_.exo_names_long, 'e_cyc2');
M_.exo_names = char(M_.exo_names, 'e_cyc3');
M_.exo_names_tex = char(M_.exo_names_tex, '\kappa_{3t}');
M_.exo_names_long = char(M_.exo_names_long, 'e_cyc3');
M_.exo_names = char(M_.exo_names, 'e_cycst1');
M_.exo_names_tex = char(M_.exo_names_tex, '\kappa^{*}_{1t}');
M_.exo_names_long = char(M_.exo_names_long, 'e_cycst1');
M_.exo_names = char(M_.exo_names, 'e_cycst2');
M_.exo_names_tex = char(M_.exo_names_tex, '\kappa^{*}_{2t}');
M_.exo_names_long = char(M_.exo_names_long, 'e_cycst2');
M_.exo_names = char(M_.exo_names, 'e_cycst3');
M_.exo_names_tex = char(M_.exo_names_tex, '\kappa^{*}_{3t}');
M_.exo_names_long = char(M_.exo_names_long, 'e_cycst3');
M_.endo_names = 'bbeta1';
M_.endo_names_tex = '\beta_{1t}';
M_.endo_names_long = 'bbeta1';
M_.endo_names = char(M_.endo_names, 'bbeta2');
M_.endo_names_tex = char(M_.endo_names_tex, '\beta_{2t}');
M_.endo_names_long = char(M_.endo_names_long, 'bbeta2');
M_.endo_names = char(M_.endo_names, 'bbeta3');
M_.endo_names_tex = char(M_.endo_names_tex, '\beta_{3t}');
M_.endo_names_long = char(M_.endo_names_long, 'bbeta3');
M_.endo_names = char(M_.endo_names, 'mmu1');
M_.endo_names_tex = char(M_.endo_names_tex, '\mu_{1t}');
M_.endo_names_long = char(M_.endo_names_long, 'mmu1');
M_.endo_names = char(M_.endo_names, 'mmu2');
M_.endo_names_tex = char(M_.endo_names_tex, '\mu_{2t}');
M_.endo_names_long = char(M_.endo_names_long, 'mmu2');
M_.endo_names = char(M_.endo_names, 'mmu3');
M_.endo_names_tex = char(M_.endo_names_tex, '\mu_{3t}');
M_.endo_names_long = char(M_.endo_names_long, 'mmu3');
M_.endo_names = char(M_.endo_names, 'ppsi1');
M_.endo_names_tex = char(M_.endo_names_tex, '\psi_{1t}');
M_.endo_names_long = char(M_.endo_names_long, 'ppsi1');
M_.endo_names = char(M_.endo_names, 'ppsi2');
M_.endo_names_tex = char(M_.endo_names_tex, '\psi_{2t}');
M_.endo_names_long = char(M_.endo_names_long, 'ppsi2');
M_.endo_names = char(M_.endo_names, 'ppsi3');
M_.endo_names_tex = char(M_.endo_names_tex, '\psi_{3t}');
M_.endo_names_long = char(M_.endo_names_long, 'ppsi3');
M_.endo_names = char(M_.endo_names, 'ppsist1');
M_.endo_names_tex = char(M_.endo_names_tex, '\psi^{*}_{1t}');
M_.endo_names_long = char(M_.endo_names_long, 'ppsist1');
M_.endo_names = char(M_.endo_names, 'ppsist2');
M_.endo_names_tex = char(M_.endo_names_tex, '\psi^{*}_{2t}');
M_.endo_names_long = char(M_.endo_names_long, 'ppsist2');
M_.endo_names = char(M_.endo_names, 'ppsist3');
M_.endo_names_tex = char(M_.endo_names_tex, '\psi^{*}_{3t}');
M_.endo_names_long = char(M_.endo_names_long, 'ppsist3');
M_.endo_names = char(M_.endo_names, 'car1');
M_.endo_names_tex = char(M_.endo_names_tex, 'car1');
M_.endo_names_long = char(M_.endo_names_long, 'car1');
M_.endo_names = char(M_.endo_names, 'car2');
M_.endo_names_tex = char(M_.endo_names_tex, 'car2');
M_.endo_names_long = char(M_.endo_names_long, 'car2');
M_.endo_names = char(M_.endo_names, 'car3');
M_.endo_names_tex = char(M_.endo_names_tex, 'car3');
M_.endo_names_long = char(M_.endo_names_long, 'car3');
M_.endo_names = char(M_.endo_names, 'carst1');
M_.endo_names_tex = char(M_.endo_names_tex, 'carst1');
M_.endo_names_long = char(M_.endo_names_long, 'carst1');
M_.endo_names = char(M_.endo_names, 'carst2');
M_.endo_names_tex = char(M_.endo_names_tex, 'carst2');
M_.endo_names_long = char(M_.endo_names_long, 'carst2');
M_.endo_names = char(M_.endo_names, 'carst3');
M_.endo_names_tex = char(M_.endo_names_tex, 'carst3');
M_.endo_names_long = char(M_.endo_names_long, 'carst3');
M_.endo_names = char(M_.endo_names, 'ym1');
M_.endo_names_tex = char(M_.endo_names_tex, 'y_{1t}');
M_.endo_names_long = char(M_.endo_names_long, 'ym1');
M_.endo_names = char(M_.endo_names, 'ym2');
M_.endo_names_tex = char(M_.endo_names_tex, 'y_{2t}');
M_.endo_names_long = char(M_.endo_names_long, 'ym2');
M_.endo_names = char(M_.endo_names, 'ym3');
M_.endo_names_tex = char(M_.endo_names_tex, 'y_{3t}');
M_.endo_names_long = char(M_.endo_names_long, 'ym3');
M_.param_names = 'rrho';
M_.param_names_tex = '\rho';
M_.param_names_long = 'rrho';
M_.param_names = char(M_.param_names, 'pphi');
M_.param_names_tex = char(M_.param_names_tex, '\phi');
M_.param_names_long = char(M_.param_names_long, 'pphi');
M_.param_names = char(M_.param_names, 'llambda');
M_.param_names_tex = char(M_.param_names_tex, '\lambda');
M_.param_names_long = char(M_.param_names_long, 'llambda');
M_.param_names = char(M_.param_names, 'a11');
M_.param_names_tex = char(M_.param_names_tex, 'a11');
M_.param_names_long = char(M_.param_names_long, 'a11');
M_.param_names = char(M_.param_names, 'a21');
M_.param_names_tex = char(M_.param_names_tex, 'a21');
M_.param_names_long = char(M_.param_names_long, 'a21');
M_.param_names = char(M_.param_names, 'a22');
M_.param_names_tex = char(M_.param_names_tex, 'a22');
M_.param_names_long = char(M_.param_names_long, 'a22');
M_.param_names = char(M_.param_names, 'a31');
M_.param_names_tex = char(M_.param_names_tex, 'a31');
M_.param_names_long = char(M_.param_names_long, 'a31');
M_.param_names = char(M_.param_names, 'a32');
M_.param_names_tex = char(M_.param_names_tex, 'a32');
M_.param_names_long = char(M_.param_names_long, 'a32');
M_.param_names = char(M_.param_names, 'a33');
M_.param_names_tex = char(M_.param_names_tex, 'a33');
M_.param_names_long = char(M_.param_names_long, 'a33');
M_.param_names = char(M_.param_names, 'ast21');
M_.param_names_tex = char(M_.param_names_tex, 'ast21');
M_.param_names_long = char(M_.param_names_long, 'ast21');
M_.param_names = char(M_.param_names, 'ast31');
M_.param_names_tex = char(M_.param_names_tex, 'ast31');
M_.param_names_long = char(M_.param_names_long, 'ast31');
M_.param_names = char(M_.param_names, 'ast32');
M_.param_names_tex = char(M_.param_names_tex, 'ast32');
M_.param_names_long = char(M_.param_names_long, 'ast32');
M_.exo_det_nbr = 0;
M_.exo_nbr = 15;
M_.endo_nbr = 21;
M_.param_nbr = 12;
M_.orig_endo_nbr = 21;
M_.aux_vars = [];
options_.varobs = [];
options_.varobs = 'ym1';
options_.varobs = char(options_.varobs, 'ym2');
options_.varobs = char(options_.varobs, 'ym3');
options_.varobs_id = [ 19 20 21  ];
M_.Sigma_e = zeros(15, 15);
M_.Correlation_matrix = eye(15, 15);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('multivariate_uoc_v1_static');
erase_compiled_function('multivariate_uoc_v1_dynamic');
M_.lead_lag_incidence = [
 1 19;
 2 20;
 3 21;
 4 22;
 5 23;
 6 24;
 7 25;
 8 26;
 9 27;
 10 28;
 11 29;
 12 30;
 13 31;
 14 32;
 15 33;
 16 34;
 17 35;
 18 36;
 0 37;
 0 38;
 0 39;]';
M_.nstatic = 3;
M_.nfwrd   = 0;
M_.npred   = 18;
M_.nboth   = 0;
M_.nsfwrd   = 0;
M_.nspred   = 18;
M_.ndynamic   = 18;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:15];
M_.maximum_lag = 1;
M_.maximum_lead = 0;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 0;
oo_.steady_state = zeros(21, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(15, 1);
M_.params = NaN(12, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 81;
M_.NNZDerivatives(2) = 0;
M_.NNZDerivatives(3) = -1;
M_.params( 1 ) = 0.7500;
rrho = M_.params( 1 );
M_.params( 2 ) = 0.7500;
pphi = M_.params( 2 );
M_.params( 3 ) = 0.2000;
llambda = M_.params( 3 );
M_.params( 5 ) = 0.0000;
a21 = M_.params( 5 );
M_.params( 7 ) = 0.0000;
a31 = M_.params( 7 );
M_.params( 8 ) = 0.0000;
a32 = M_.params( 8 );
M_.params( 10 ) = 0.0000;
ast21 = M_.params( 10 );
M_.params( 11 ) = 0.0000;
ast31 = M_.params( 11 );
M_.params( 12 ) = 0.0000;
ast32 = M_.params( 12 );
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(10, 10) = (1.0000)^2;
M_.Sigma_e(11, 11) = (1.0000)^2;
M_.Sigma_e(12, 12) = (1.0000)^2;
M_.Sigma_e(13, 13) = (1.0000)^2;
M_.Sigma_e(14, 14) = (1.0000)^2;
M_.Sigma_e(15, 15) = (1.0000)^2;
global estim_params_
estim_params_.var_exo = [];
estim_params_.var_endo = [];
estim_params_.corrx = [];
estim_params_.corrn = [];
estim_params_.param_vals = [];
estim_params_.param_vals = [estim_params_.param_vals; 1, NaN, (-Inf), Inf, 1, 0.75, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 2, NaN, (-Inf), Inf, 1, 0.75, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 3, NaN, (-Inf), Inf, 3, 0.20, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 4, NaN, (-Inf), Inf, 4, 0.005, Inf, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 6, NaN, (-Inf), Inf, 4, 0.005, Inf, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 9, NaN, (-Inf), Inf, 4, 0.005, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 1, NaN, (-Inf), Inf, 4, 0.005, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, NaN, (-Inf), Inf, 4, 0.005, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, NaN, (-Inf), Inf, 4, 0.005, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, NaN, (-Inf), Inf, 4, 0.001, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 5, NaN, (-Inf), Inf, 4, 0.001, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, NaN, (-Inf), Inf, 4, 0.001, Inf, NaN, NaN, NaN ];
estim_params_.corrx = [estim_params_.corrx; 4 5, NaN, (-Inf), Inf, 1, 0.00, 0.30, (-1), 1, NaN ];
estim_params_.corrx = [estim_params_.corrx; 4 6, NaN, (-Inf), Inf, 1, 0.00, 0.30, (-1), 1, NaN ];
estim_params_.corrx = [estim_params_.corrx; 5 6, NaN, (-Inf), Inf, 1, 0.00, 0.30, (-1), 1, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 7, NaN, (-Inf), Inf, 4, 0.001, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 8, NaN, (-Inf), Inf, 4, 0.001, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 9, NaN, (-Inf), Inf, 4, 0.001, Inf, NaN, NaN, NaN ];
estim_params_.corrx = [estim_params_.corrx; 7 8, NaN, (-Inf), Inf, 1, 0.00, 0.30, (-1), 1, NaN ];
estim_params_.corrx = [estim_params_.corrx; 7 9, NaN, (-Inf), Inf, 1, 0.00, 0.30, (-1), 1, NaN ];
estim_params_.corrx = [estim_params_.corrx; 8 9, NaN, (-Inf), Inf, 1, 0.00, 0.30, (-1), 1, NaN ];
options_.diffuse_filter = 1;
options_.filtered_vars = 1;
options_.forecast = 0;
options_.kalman_algo = 0;
options_.mh_nblck = 1;
options_.mh_replic = 100;
options_.mode_compute = 6;
options_.nodiagnostic = 1;
options_.nodisplay = 1;
options_.plot_priors = 0;
options_.smoother = 1;
options_.datafile = 'US_data';
options_.graph_format=[];
options_.graph_format = 'pdf';
options_.order = 1;
options_.steadystate.nocheck = 1;
var_list_=[];
var_list_ = 'mmu1';
var_list_ = char(var_list_, 'mmu2');
var_list_ = char(var_list_, 'mmu3');
var_list_ = char(var_list_, 'car1');
var_list_ = char(var_list_, 'car2');
var_list_ = char(var_list_, 'car3');
dynare_estimation(var_list_);
US_data;
stat_		= 'Mean';
label_		= { 'US log real GDP', 'US log real Credit', 'US log real House Prices' };
for i = 1:3
	eval([ 'ym_	= ym' 					 num2str(i) ';' ]);
	eval([ 'trend_ 	= oo_.SmoothedVariables.' stat_ '.mmu'   num2str(i) ';' ]);
	eval([ 'cycle_ 	= oo_.SmoothedVariables.' stat_ '.car'   num2str(i) ';' ]);
	eval([ 'irreg_ 	= oo_.SmoothedShocks.'    stat_ '.e_irr' num2str(i) ';' ]);
	graphs_UOC( Date, ym_, trend_, cycle_, irreg_, [ 'Series: ' label_{i} ] );
end;
save('multivariate_uoc_v1_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('multivariate_uoc_v1_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('multivariate_uoc_v1_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('multivariate_uoc_v1_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('multivariate_uoc_v1_results.mat', 'estimation_info', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
